development:
  adapter: postgresql
  host: localhost
  port: 5432
  database: classifieds_development


test:
  adapter: postgresql
  encoding: unicode
  database: classifieds_test
  pool: 5
  host: localhost
  port: 5432


production:
  adapter: postgresql
  encoding: unicode
  database: classifieds_production
  pool: 5
  host: localhost
  port: 5432

